export enum ENTITY_TYPES {
    BOOKING = 1,
    CUSTOMER = 2,
    USER = 3,
    COMMERCE = 4,
    SERVICE = 5,
    USER_CONFIG = 6,
    COMMERCE_CONFIG = 7,
    USER_WORKING_OVERRIDE = 8,
    COMMERCE_WORKING_OVERRIDE = 9,
    USER_WORKING_PATTERN = 10,
    COMMERCE_WORKING_PATTERN = 11,
}

export enum CHANGE_TYPES {
    CREATED = 1,
    UPDATED = 2,
    CANCELLED = 3,
    SUSPENDED = 4,
    REINSTATED = 5,
}