-- AlterTable
ALTER TABLE "CustomerCommerce" ALTER COLUMN "firstReservationAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "periodStart" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "periodEnd" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "generatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "MercadoPago" ALTER COLUMN "tokenExpires" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "refundedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "activity_logs" ALTER COLUMN "timestamp" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "booking_histories" ALTER COLUMN "timeStart" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "timeEnd" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "bookings" ALTER COLUMN "timeEnd" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "timeStart" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "commerce_working_overrides" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "reminders" ALTER COLUMN "scheduledAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "sentAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "user_working_overrides" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ;
